feat: add and test actions workflow for pull requests issued to main …
tech-university-india/k8s-designer-frontend pull request #2
Opened 2023-02-11 17:17 UTC by PreetinderSingh345

2023-02-11 17:19 UTC, PreetinderSingh345 commented
Will create another GitHub token to test the workflow

2023-02-11 17:28 UTC, PreetinderSingh345 commented
The docker image is pushed to the current repository's packages. Therefore permission is needed inside Settings>Actions>General>Workflow Permissions to allow read and write permissions for the current repository. Please allow those permissions, for all the tests to pass.

2023-02-11 18:47 UTC, AshreneRoy commented
> The docker image is pushed to the current repository's packages. Therefore permission is needed inside Settings>Actions>General>Workflow Permissions to allow read and write permissions for the current repository. Please allow those permissions, for all the tests to pass.

Looks like I don't have the permission to do this, it rests with Org owners. @Ar11rA @rkdixit96 can you please help out with above for this repo, here's the link to the settings page: https://github.com/tech-university-india/k8s-designer-frontend/settings/actions

2023-02-11 18:57 UTC, AshreneRoy requested changes

2023-02-11 18:57 UTC, AshreneRoy commented on .github/workflows/buildAndDeploy.yml
> +  USER: preetindersingh345
Do we need user?

2023-02-11 18:57 UTC, AshreneRoy commented on .github/workflows/buildAndDeploy.yml
> +        echo ${{env.PAT}} | docker login ${{env.REGISTRY}} -u ${{env.USER}} --password-stdin
Let's not echo secrets

2023-02-11 18:57 UTC, AshreneRoy commented on .github/workflows/buildAndDeploy.yml
> +        echo ${{env.PAT}} | docker login ${{env.REGISTRY}} -u ${{env.USER}} --password-stdin
GITHUB_TOKEN is already in env, no need to create another env to store it

2023-02-11 18:57 UTC, AshreneRoy commented on .github/workflows/buildAndDeploy.yml
> +  IMAGE_NAME: docker-image-name
This should follow repo name

2023-02-11 18:57 UTC, AshreneRoy commented on .github/workflows/buildAndDeploy.yml
> +        docker tag ${{env.IMAGE_NAME}} ${{env.REGISTRY}}/${{env.USER}}/${{env.IMAGE_NAME}}:${{env.TAG}}
Follow naming convention like: 
`<repo_name>:<semVer>-<last_7_digits_of_commit_sha>`

2023-02-11 19:00 UTC, AshreneRoy commented on .github/workflows/buildAndDeploy.yml
> +name: Build and Deploy
We should also test the code base for linting and tests before building and pushing images

2023-02-11 19:08 UTC, AshreneRoy commented on .github/workflows/buildAndDeploy.yml
> +name: Build and Deploy
In this workflow, rename the file and keep only the npm run commands for installing packages, checking linting, testing etc.

2023-02-12 11:08 UTC, PreetinderSingh345 commented
Made the mentioned changes for this branch.

2023-02-12 11:14 UTC, PreetinderSingh345 commented on .github/workflows/buildAndDeploy.yml
> +  USER: preetindersingh345
The image will be pushed to the packages section for the repository and we need to add the user/owner to whom the repository belongs.

2023-02-12 11:14 UTC, AshreneRoy approved these changes

2023-02-12 11:15 UTC, merged

2023-02-12 11:21 UTC, PreetinderSingh345 commented on .github/workflows/buildAndDeploy.yml
> +  IMAGE_NAME: docker-image-name
I'll change it to tech-university-india

2023-02-12 11:38 UTC, PreetinderSingh345 commented on .github/workflows/buildAndDeploy.yml
> +        echo ${{env.PAT}} | docker login ${{env.REGISTRY}} -u ${{env.USER}} --password-stdin
I've added` >/dev/null 2>&1` after the echo statement, it'll suppress the output of the shell script command and the secret will not be visible in the logs.